base_url = "https://edibotopic.com"
title = "edibotopic"
description = "food | technology | philosophy"
default_language = "en"
theme = "serene"
output_dir = "docs"
compile_sass = true
minify_html = true
build_search_index = false
generate_feeds = false
feed_filenames = ["feed.xml"]
taxonomies = [
    {name = "tags"},
    {name = "categories"}
]

[markdown]
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["highlight_themes"]
highlight_themes_css = [
    { theme = "serene-light", filename = "hl-light.css"},
    { theme = "serene-dark", filename = "hl-dark.css"},
]
render_emoji = true
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
name = "Shane Crowley"
id = "edibotopic"
bio = "Food | Technology | Philosophy"
avatar = "img/avatar.svg"

display_id = true
projects_page = true
blog_categorized = true
blur_effect = true

toc = true
comment = false
copy = false
back_to_top = true

nav_separator = "::"

links = [
    {name = "GitHub", icon = "github", url = "https://github.com/edibotopic"},
    {name = "Email", icon = "email", url = "mailto:edibotopic@gmail.com"},
    {name = "RSS", icon = "rss", url = "https://edibotopic.com/blog/feed.xml"},
]

feed_in_blog_section = true # Feed file in blog section, url will be https://edibotopic.com/blog/feed.xml

outdate_alert = false
outdate_alert_days = 120
outdate_alert_text_before = "This article was last updated "
outdate_alert_text_after = " days ago and may be out of date."

footer_copyright = "© edibotopic | 2024"
footer_credits = false
