[[collection]]
type = "art_simple"
img = "/art/dollops.jpg"
link = "https://curtsyrehearsed.bandcamp.com/album/dollops"
title = "Dollops"

[[collection]]
type = "art_simple"
img = "/art/formal-garden.jpg"
link = "https://curtsyrehearsed.bandcamp.com/album/formal-garden"
title = "Formal Garden"

[[collection]]
type = "art_simple"
img = "/art/tough-centra.jpg"
link = "https://curtsyrehearsed.bandcamp.com/album/tough-centras"
title = "Tough Centras"

[[collection]]
type = "art_simple"
img = "/art/trash-heat.jpg"
link = "https://curtsyrehearsed.bandcamp.com/album/trash-heat"
title = "Trash Heat"

[[collection]]
type = "art_simple"
img = "/art/eluded.jpg"
link = "https://curtsyrehearsed.bandcamp.com/album/leisure-sick"
title = "Leisure Sick"

[[collection]]
type = "art_simple"
img = "/art/mulcahy.jpg"
link = "https://curtsyrehearsed.bandcamp.com/album/mulcahy"
title = "Mulcahy"

[[collection]]
type = "art_simple"
img = "/art/calmlies.jpg"
link = "https://curtsyrehearsed.bandcamp.com/album/calmlies"
title = "Calmlies"

[[collection]]
type = "art_simple"
img = "/art/kinds-of-summer.jpg"
link = "https://curtsyrehearsed.bandcamp.com/album/kinds-of-summer"
title = "Kinds of Summer"

[[collection]]
type = "art_simple"
img = "/art/punctums.jpg"
link = "https://curtsyrehearsed.bandcamp.com/album/punctums"
title = "Punctums"

[[collection]]
type = "art_simple"
img = "/art/insistence.jpg"
link = "https://curtsyrehearsed.bandcamp.com/album/insistence"
title = "Insistence"

[[collection]]
type = "art_simple"
img = "/art/newly-sincere.jpg"
link = "https://curtsyrehearsed.bandcamp.com/album/newly-sincere"
title = "Newly Sincere"

[[collection]]
type = "art_simple"
img = "/art/micro-noirs.jpg"
link = "https://curtsyrehearsed.bandcamp.com/album/micro-noirs"
title = "Micro Noirs"

[[collection]]
type = "art_simple"
img = "/art/micro-saliences.jpg"
link = "https://curtsyrehearsed.bandcamp.com/album/micro-saliences"
title = "Micro Saliences"
