[[project]]
name = "WriteHeight"
desc = "A web-based tool for converting greyscale images to 3D models for download and use."
tags = ["software", "3D"]
img = "/figs/writeHeightUI.webp"
links = [
	{name = "website", url = "https://edibotopic.github.io/write-height/"},
	{name = "source", url = "https://github.com/edibotopic/write-height/"},
	{name = "blog", url = "https://edibotopic.com/blog/doing/write-height/"}
]

[[project]]
name = "Stokes' Law"
desc = "An interactive web-based visualiser and calculator for Stokes' Law."
img = "/figs/stokesLawUI.webp"
tags = ["software", "teaching"]
links = [
	{name = "website", url = "https://edibotopic.github.io/stokes-law/"},
	{name = "source", url = "https://github.com/edibotopic/stokes-law/"},
	{name = "paper", url = "https://pubs.acs.org/doi/10.1021/acs.jchemed.2c01201"},
	{name = "blog", url = "https://edibotopic.com/blog/doing/stokes-law/"}
]

[[project]]
name = "Curtsy Rehearsed"
desc = "Original music about memories, nature and technology (active 2021-present)"
img = "/figs/curtsyLatest.webp"
tags = ["music", "art"]
links = [
	{name = "bandcamp", url = "https://curtsyrehearsed.bandcamp.com"},
	{name = "blog", url = "https://edibotopic.com/blog/doing/curtsy-rehearsed/"},
	{name = "press", url = "https://www.echolive.ie/entertainment/whatson/arid-40902209.html"}
]

[[project]]
name = "Food Metaphors"
desc = "Philosophical article written for the book Metaphors, Sustainability, Transformation."
img = "/figs/metaphorBook.webp"
tags = ["philosophy", "writing"]
links = [
	{name = "website", url = "https://www.taylorfrancis.com/chapters/edit/10.4324/9781003143567-5/alchemical-cyborgian-imaginings-technoscientific-discourse-relating-holistic-turns-food-processing-personalised-nutrition-shane-crowley"},
]

[[project]]
name = "Scientific publications"
desc = "Over 60 publications on the science and technology of food systems."
tags = ["research", "science"]
links = [
	{name = "GoogleScholar", url = "https://scholar.google.com/citations?user=aw1EnaIAAAAJ&hl=en"},
	{name = "ResearchGate", url = "https://www.researchgate.net/profile/Shane-Crowley"},
]

[[project]]
name = "TRANSFORM"
desc = "Four-year project on dietary technology for cancer patients where I developed the concept, planned the project and led the proposal writing."
tags = ["research", "science"]
links = [
	{name = "Project website", url = "https://sites.google.com/view/thetransfromproject?usp=sharing"},
]

[[project]]
name = "RUBUSElite"
desc = "Four-year project on a sports nutrition beverage where I co-wrote the proposal and supervised a 4-year PhD project."
tags = ["research", "science"]
links = [
	{name = "Project overview", url = "https://www.ucc.ie/en/vitamind/history/rubuselite/"},
]

[[project]]
name = "PhD thesis"
desc = "Physicochemical characterisation of protein ingredients prepared from milk by ultrafiltration or microfiltration for application in formulated nutritional products"
tags = ["research", "science"]
links = [
	{name = "Open access version", url = "https://cora.ucc.ie/items/64a3a7b0-b19a-41c9-bc4d-4ba051998055"},
]
