[[collection]]
type = "card_simple"
# icon = "/assets/icon-deepseek.svg"
title = "South East Technological University"
content = "HDip Computer Science"
date = "2024-present"

[[collection]]
type = "card_simple"
# icon = "/assets/icon-deepseek.svg"
title = "University College Cork"
content = "HDip Philosophy"
date = "2018-2020"

[[collection]]
type = "card_simple"
# icon = "/assets/icon-deepseek.svg"
title = "University College Cork"
content = "Cert. Teaching & Learning for Higher Education"
date = "2017-2018"

[[collection]]
type = "card_simple"
# icon = "/assets/icon-deepseek.svg"
title = "University College Cork"
content = "PhD Food Science & Technology"
date = "2012-2016"

[[collection]]
type = "card_simple"
# icon = "/assets/icon-deepseek.svg"
title = "University College Cork"
content = "BSc Food Science"
date = "2008-2012"
