[[project]]
name = "Stokes's Law"
desc = "An interactive visualiser and calculator for Stoke's Law, which describes the factors that influence how particles sink and float in liquids."
links = [
	{name = "website", url = "https://edibotopic.github.io/stokes-law/"},
	{name = "source", url = "https://github.com/edibotopic/stokes-law/"}
]

[[project]]
name = "Curtsy Rehearsed"
desc = "Sample-based music about memories, nature and technology (free or pay-what-you-want)."
links = [
	{name = "bandcamp", url = "https://curtsyrehearsed.bandcamp.com"},
]

[[project]]
name = "Food Metaphors"
desc = "Philosophical work that was written for the recent book Metaphors, Sustainability, Transformation."
links = [
	{name = "website", url = "https://www.taylorfrancis.com/chapters/edit/10.4324/9781003143567-5/alchemical-cyborgian-imaginings-technoscientific-discourse-relating-holistic-turns-food-processing-personalised-nutrition-shane-crowley"},
]

[[project]]
name = "Sqong"
desc = "A simple Pong-clone written in the Odin programming language using the Raylib library."
links = [
	{name = "source", url = "https://github.com/edibotopic/sqong/"}
]

[[project]]
name = "WriteHeight"
desc = "A web-based tool for converting heightmaps to 3D models (work-in-progress)."
links = [
	{name = "website", url = "https://edibotopic.github.io/write-height/"},
	{name = "source", url = "https://github.com/edibotopic/write-height/"}
]

[[project]]
name = "Food Science"
desc = "General projects on the science and technology of food systems (too numerous to list)."
links = [
	{name = "GoogleScholar", url = "https://scholar.google.com/citations?user=aw1EnaIAAAAJ&hl=en"},
	{name = "ResearchGate", url = "https://www.researchgate.net/profile/Shane-Crowley"},
]
