[[project]]
name = "WriteHeight"
desc = "A web-based tool for converting greyscale images to 3D models for download and use."
tags = ["software", "3D"]
links = [
	{name = "website", url = "https://edibotopic.github.io/write-height/"},
	{name = "source", url = "https://github.com/edibotopic/write-height/"},
	{name = "blog", url = "https://edibotopic.com/blog/doing/write-height/"}
]

[[project]]
name = "Stokes' Law"
desc = "An interactive web-based visualiser and calculator for Stokes' Law, which describes the factors that influence how particles sink and float in fluids."
tags = ["software", "teaching"]
links = [
	{name = "website", url = "https://edibotopic.github.io/stokes-law/"},
	{name = "source", url = "https://github.com/edibotopic/stokes-law/"},
	{name = "paper", url = "https://pubs.acs.org/doi/10.1021/acs.jchemed.2c01201"},
	{name = "blog", url = "https://edibotopic.com/blog/doing/stokes-law/"}
]

[[project]]
name = "Curtsy Rehearsed"
desc = "Original music about memories, nature and technology (active 2021-present)."
tags = ["music", "art"]
links = [
	{name = "bandcamp", url = "https://curtsyrehearsed.bandcamp.com"},
	{name = "blog", url = "https://edibotopic.com/blog/doing/curtsy-rehearsed/"},
	{name = "press", url = "https://www.echolive.ie/entertainment/whatson/arid-40902209.html"}
]

[[project]]
name = "Food Metaphors"
desc = "Philosophical article written for the recent book Metaphors, Sustainability, Transformation."
tags = ["philosophy", "writing"]
links = [
	{name = "website", url = "https://www.taylorfrancis.com/chapters/edit/10.4324/9781003143567-5/alchemical-cyborgian-imaginings-technoscientific-discourse-relating-holistic-turns-food-processing-personalised-nutrition-shane-crowley"},
]

[[project]]
name = "DSF-racket"
desc = "A tool written in Racket for visualising and iterating spatial topologies represented in symbolic notation."
tags = ["software", "science"]
links = [
	{name = "source", url = "https://github.com/edibotopic/dsf-racket/"}
]

[[project]]
name = "TRANSFORM"
desc = "Four-year project on dietary technology for cancer patients where I developed the concept, planned the project and led the proposal writing."
tags = ["research", "science"]
links = [
]

[[project]]
name = "RUBUSElite"
desc = "Four-year project on a sports nutrition beverage where I co-wrote the proposal and supervised a 4-year PhD project."
tags = ["research", "science"]
links = [
	{name = "Overview", url = "https://www.ucc.ie/en/vitamind/history/rubuselite/"},
]

[[project]]
name = "Scientific publications"
desc = "Around 70 papers on the science and technology of food systems."
tags = ["research", "science"]
links = [
	{name = "GoogleScholar", url = "https://scholar.google.com/citations?user=aw1EnaIAAAAJ&hl=en"},
	{name = "ResearchGate", url = "https://www.researchgate.net/profile/Shane-Crowley"},
]
